import React from 'react'
import { motion, useScroll } from "framer-motion"
import "./App.css"

//userscroll,whileTap,WhileHover,Drag,Drag-Constraints,Drag-Lock Learnt
function App() {
  const {scrollYProgress}=useScroll()

  return (
    <>
    <div >
    <motion.div className='font-mono fixed top-0 w-full h-2 bg-red-500 left-0 origin-left' style={{scaleX:scrollYProgress,}}></motion.div>
<div>
             <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi rem nam perferendis minima minus dicta consectetur ab a tempora ducimus, nemo laudantium accusamus autem consequatur. Sint quae exercitationem, voluptate maxime necessitatibus eius quisquam nostrum in ullam consequuntur reiciendis voluptatum fugiat laboriosam modi esse. Dignissimos pariatur provident quisquam esse amet perferendis eaque modi magnam corrupti cum vitae, dolor quae exercitationem at facilis. Eos beatae libero error nemo quidem blanditiis vitae iste adipisci magnam expedita velit reprehenderit, atque architecto quo repellat ipsa nulla quis nobis et alias asperiores pariatur! Aliquam sequi delectus non voluptate! Obcaecati blanditiis eius quod assumenda laborum ipsum ut earum nemo tempora provident commodi quisquam unde rem itaque adipisci doloremque, quasi modi similique sapiente in voluptatum. Itaque aspernatur amet omnis, deleniti autem voluptatibus distinctio iste, est illo quidem fuga quasi aut molestias sapiente harum illum! Voluptatibus vel quibusdam explicabo, quasi architecto deleniti possimus pariatur voluptate blanditiis nostrum, cupiditate mollitia quam tempore culpa eius repellendus obcaecati perspiciatis, molestias consequuntur! Odit eius necessitatibus iure nemo nostrum, non saepe omnis fugiat, mollitia voluptatibus porro explicabo unde accusamus harum nulla ex nam modi enim tempora architectAo, beatae dolorem? Ab sit amet, accusamus sint nemo quam cum, quis rerum quibusdam repellat dolorem reprehenderit autem?</h1><br />
             <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi rem nam perferendis minima minus dicta consectetur ab a tempora ducimus, nemo laudantium accusamus autem consequatur. Sint quae exercitationem, voluptate maxime necessitatibus eius quisquam nostrum in ullam consequuntur reiciendis voluptatum fugiat laboriosam modi esse. Dignissimos pariatur provident quisquam esse amet perferendis eaque modi magnam corrupti cum vitae, dolor quae exercitationem at facilis. Eos beatae libero error nemo quidem blanditiis vitae iste adipisci magnam expedita velit reprehenderit, atque architecto quo repellat ipsa nulla quis nobis et alias asperiores pariatur! Aliquam sequi delectus non voluptate! Obcaecati blanditiis eius quod assumenda laborum ipsum ut earum nemo tempora provident commodi quisquam unde rem itaque adipisci doloremque, quasi modi similique sapiente in voluptatum. Itaque aspernatur amet omnis, deleniti autem voluptatibus distinctio iste, est illo quidem fuga quasi aut molestias sapiente harum illum! Voluptatibus vel quibusdam explicabo, quasi architecto deleniti possimus pariatur voluptate blanditiis nostrum, cupiditate mollitia quam tempore culpa eius repellendus obcaecati perspiciatis, molestias consequuntur! Odit eius necessitatibus iure nemo nostrum, non saepe omnis fugiat, mollitia voluptatibus porro explicabo unde accusamus harum nulla ex nam modi enim tempora architecto, beatae dolorem? Ab sit amet, accusamus sint nemo quam cum, quis rerum quibusdam repellat dolorem reprehenderit autem?</h1><br />
             <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi rem nam perferendis minima minus dicta consectetur ab a tempora ducimus, nemo laudantium accusamus autem consequatur. Sint quae exercitationem, voluptate maxime necessitatibus eius quisquam nostrum in ullam consequuntur reiciendis voluptatum fugiat laboriosam modi esse. Dignissimos pariatur provident quisquam esse amet perferendis eaque modi magnam corrupti cum vitae, dolor quae exercitationem at facilis. Eos beatae libero error nemo quidem blanditiis vitae iste adipisci magnam expedita velit reprehenderit, atque architecto quo repellat ipsa nulla quis nobis et alias asperiores pariatur! Aliquam sequi delectus non voluptate! Obcaecati blanditiis eius quod assumenda laborum ipsum ut earum nemo tempora provident commodi quisquam unde rem itaque adipisci doloremque, quasi modi similique sapiente in voluptatum. Itaque aspernatur amet omnis, deleniti autem voluptatibus distinctio iste, est illo quidem fuga quasi aut molestias sapiente harum illum! Voluptatibus vel quibusdam explicabo, quasi architecto deleniti possimus pariatur voluptate blanditiis nostrum, cupiditate mollitia quam tempore culpa eius repellendus obcaecati perspiciatis, molestias consequuntur! Odit eius necessitatibus iure nemo nostrum, non saepe omnis fugiat, mollitia voluptatibus porro explicabo unde accusamus harum nulla ex nam modi enim tempora architecto, beatae dolorem? Ab sit amet, accusamus sint nemo quam cum, quis rerum quibusdam repellat dolorem reprehenderit autem?</h1><br />
             <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi rem nam perferendis minima minus dicta consectetur ab a tempora ducimus, nemo laudantium accusamus autem consequatur. Sint quae exercitationem, voluptate maxime necessitatibus eius quisquam nostrum in ullam consequuntur reiciendis voluptatum fugiat laboriosam modi esse. Dignissimos pariatur provident quisquam esse amet perferendis eaque modi magnam corrupti cum vitae, dolor quae exercitationem at facilis. Eos beatae libero error nemo quidem blanditiis vitae iste adipisci magnam expedita velit reprehenderit, atque architecto quo repellat ipsa nulla quis nobis et alias asperiores pariatur! Aliquam sequi delectus non voluptate! Obcaecati blanditiis eius quod assumenda laborum ipsum ut earum nemo tempora provident commodi quisquam unde rem itaque adipisci doloremque, quasi modi similique sapiente in voluptatum. Itaque aspernatur amet omnis, deleniti autem voluptatibus distinctio iste, est illo quidem fuga quasi aut molestias sapiente harum illum! Voluptatibus vel quibusdam explicabo, quasi architecto deleniti possimus pariatur voluptate blanditiis nostrum, cupiditate mollitia quam tempore culpa eius repellendus obcaecati perspiciatis, molestias consequuntur! Odit eius necessitatibus iure nemo nostrum, non saepe omnis fugiat, mollitia voluptatibus porro explicabo unde accusamus harum nulla ex nam modi enim tempora architecto, beatae dolorem? Ab sit amet, accusamus sint nemo quam cum, quis rerum quibusdam repellat dolorem reprehenderit autem?</h1><br />
             <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi rem nam perferendis minima minus dicta consectetur ab a tempora ducimus, nemo laudantium accusamus autem consequatur. Sint quae exercitationem, voluptate maxime necessitatibus eius quisquam nostrum in ullam consequuntur reiciendis voluptatum fugiat laboriosam modi esse. Dignissimos pariatur provident quisquam esse amet perferendis eaque modi magnam corrupti cum vitae, dolor quae exercitationem at facilis. Eos beatae libero error nemo quidem blanditiis vitae iste adipisci magnam expedita velit reprehenderit, atque architecto quo repellat ipsa nulla quis nobis et alias asperiores pariatur! Aliquam sequi delectus non voluptate! Obcaecati blanditiis eius quod assumenda laborum ipsum ut earum nemo tempora provident commodi quisquam unde rem itaque adipisci doloremque, quasi modi similique sapiente in voluptatum. Itaque aspernatur amet omnis, deleniti autem voluptatibus distinctio iste, est illo quidem fuga quasi aut molestias sapiente harum illum! Voluptatibus vel quibusdam explicabo, quasi architecto deleniti possimus pariatur voluptate blanditiis nostrum, cupiditate mollitia quam tempore culpa eius repellendus obcaecati perspiciatis, molestias consequuntur! Odit eius necessitatibus iure nemo nostrum, non saepe omnis fugiat, mollitia voluptatibus porro explicabo unde accusamus harum nulla ex nam modi enim tempora architecto, beatae dolorem? Ab sit amet, accusamus sint nemo quam cum, quis rerum quibusdam repellat dolorem reprehenderit autem?</h1><br />
             <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi rem nam perferendis minima minus dicta consectetur ab a tempora ducimus, nemo laudantium accusamus autem consequatur. Sint quae exercitationem, voluptate maxime necessitatibus eius quisquam nostrum in ullam consequuntur reiciendis voluptatum fugiat laboriosam modi esse. Dignissimos pariatur provident quisquam esse amet perferendis eaque modi magnam corrupti cum vitae, dolor quae exercitationem at facilis. Eos beatae libero error nemo quidem blanditiis vitae iste adipisci magnam expedita velit reprehenderit, atque architecto quo repellat ipsa nulla quis nobis et alias asperiores pariatur! Aliquam sequi delectus non voluptate! Obcaecati blanditiis eius quod assumenda laborum ipsum ut earum nemo tempora provident commodi quisquam unde rem itaque adipisci doloremque, quasi modi similique sapiente in voluptatum. Itaque aspernatur amet omnis, deleniti autem voluptatibus distinctio iste, est illo quidem fuga quasi aut molestias sapiente harum illum! Voluptatibus vel quibusdam explicabo, quasi architecto deleniti possimus pariatur voluptate blanditiis nostrum, cupiditate mollitia quam tempore culpa eius repellendus obcaecati perspiciatis, molestias consequuntur! Odit eius necessitatibus iure nemo nostrum, non saepe omnis fugiat, mollitia voluptatibus porro explicabo unde accusamus harum nulla ex nam modi enim tempora architecto, beatae dolorem? Ab sit amet, accusamus sint nemo quam cum, quis rerum quibusdam repellat dolorem reprehenderit autem?</h1><br />
             <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi rem nam perferendis minima minus dicta consectetur ab a tempora ducimus, nemo laudantium accusamus autem consequatur. Sint quae exercitationem, voluptate maxime necessitatibus eius quisquam nostrum in ullam consequuntur reiciendis voluptatum fugiat laboriosam modi esse. Dignissimos pariatur provident quisquam esse amet perferendis eaque modi magnam corrupti cum vitae, dolor quae exercitationem at facilis. Eos beatae libero error nemo quidem blanditiis vitae iste adipisci magnam expedita velit reprehenderit, atque architecto quo repellat ipsa nulla quis nobis et alias asperiores pariatur! Aliquam sequi delectus non voluptate! Obcaecati blanditiis eius quod assumenda laborum ipsum ut earum nemo tempora provident commodi quisquam unde rem itaque adipisci doloremque, quasi modi similique sapiente in voluptatum. Itaque aspernatur amet omnis, deleniti autem voluptatibus distinctio iste, est illo quidem fuga quasi aut molestias sapiente harum illum! Voluptatibus vel quibusdam explicabo, quasi architecto deleniti possimus pariatur voluptate blanditiis nostrum, cupiditate mollitia quam tempore culpa eius repellendus obcaecati perspiciatis, molestias consequuntur! Odit eius necessitatibus iure nemo nostrum, non saepe omnis fugiat, mollitia voluptatibus porro explicabo unde accusamus harum nulla ex nam modi enim tempora architecto, beatae dolorem? Ab sit amet, accusamus sint nemo quam cum, quis rerum quibusdam repellat dolorem reprehenderit autem?</h1><br />
</div>
    
    </div>
    <div>
      Lorem ipsum dolor sit, amet consectetur adipisicing elit. Numquam aperiam ipsa, quas beatae ducimus debitis dolorem aliquam id odit! Omnis, labore nisi. Sit, nihil accusamus maiores at voluptate neque unde cupiditate laudantium harum saepe, velit numquam dolorem doloremque nemo autem explicabo nulla quidem eaque aperiam. Accusantium quisquam repellat eaque ea illum magnam, dignissimos voluptate quia vero in magni iure culpa necessitatibus deleniti libero, et nisi? Quod fuga minima accusantium enim ipsam. Nobis minima libero, inventore itaque officiis tempora quas quam suscipit explicabo velit facere magnam, debitis exercitationem repudiandae necessitatibus dolorem distinctio consequuntur beatae. Unde eligendi consequatur delectus accusamus, earum facere fugit, dicta aspernatur ex omnis tenetur sunt. Cumque voluptatem iusto exercitationem minima consequatur perferendis praesentium aliquam placeat rem, non ipsum quis debitis reiciendis. Suscipit temporibus fugit beatae soluta natus officia fugiat molestias quaerat porro dolore. Similique officia illo distinctio veritatis, tenetur necessitatibus repudiandae libero sint! Laboriosam, tempora. Exercitationem corporis dolores beatae in, esse tenetur error consequatur maxime cumque ipsam, at repellendus a? Voluptatibus, sint a corrupti voluptate suscipit commodi nisi unde corporis asperiores inventore odio harum quas. Nisi eaque optio commodi sint excepturi iste, explicabo odit modi quaerat numquam, doloribus rerum cumque nam quisquam veniam mollitia vero qui tempore doloremque.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni laborum est quisquam ea adipisci dignissimos voluptatem quis ut, magnam voluptates reprehenderit eius? Ratione quia nobis non quam amet illum, iure possimus impedit debitis dolorum veritatis saepe alias magnam inventore earum aliquam? Quae mollitia ad eum ea illum nostrum rerum, at sint, quo suscipit tempora optio, corporis saepe culpa magni. Aspernatur temporibus voluptas quam aliquam facilis rem tempore dicta fuga, magnam incidunt nulla animi? Officiis sunt amet commodi, odit consectetur magni voluptatem possimus hic nam provident corporis dignissimos ducimus voluptatibus assumenda quod ullam. Cum officiis corrupti atque obcaecati quas, a autem minima animi et consequuntur accusantium quae quam fugiat illo ipsa temporibus laboriosam asperiores voluptatibus ex eum suscipit expedita. Ipsum illo expedita quo, quas voluptatem, beatae, inventore aperiam possimus repellat quisquam doloremque. Laborum corrupti a rerum? Molestiae enim officiis alias magnam quas nisi non voluptatum ipsum quidem temporibus excepturi numquam labore quam eligendi unde, reiciendis reprehenderit ab ipsa eius qui. Dolore, exercitationem placeat. Qui repudiandae debitis beatae iusto odio adipisci perspiciatis pariatur, deleniti nihil reprehenderit accusamus quis recusandae nesciunt tempora consectetur, neque saepe natus ab necessitatibus officia optio deserunt tenetur! Nulla esse laboriosam eligendi commodi beatae qui tempora et voluptatibus iste.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. A, minima sint earum recusandae possimus labore quisquam voluptates ipsam, sit nostrum veritatis quasi repellendus cumque placeat doloribus. Doloremque, accusantium harum vero expedita tenetur quae explicabo dolores voluptatibus minima repellat blanditiis assumenda at dolor molestiae omnis velit, cum itaque quam officia magni eaque impedit ut earum! Eos vitae nemo maiores nostrum veritatis quaerat sapiente sed tenetur suscipit exercitationem minus aut qui aspernatur adipisci cumque unde architecto expedita ab nulla neque, consequuntur iusto natus! Esse ex tempora earum ipsa eveniet! Corrupti deleniti tempore sint quam necessitatibus obcaecati repudiandae sit dicta voluptas, dolore alias, quaerat perspiciatis deserunt nesciunt praesentium autem eum incidunt magnam. Quia eos ad debitis omnis doloremque laudantium ipsa praesentium tenetur hic, labore accusantium ipsum, vero, nostrum nam velit sunt molestias modi fuga minus iure. Pariatur ex aspernatur, dolorem similique maxime iste dolor consectetur tempora fuga facere provident quos modi ullam possimus perspiciatis, quasi, laboriosam consequuntur ducimus impedit. Nulla omnis doloremque corporis vero vitae similique harum perspiciatis necessitatibus eum totam soluta officia, cumque quas distinctio delectus exercitationem aperiam tempora porro ipsa eos eligendi. Laborum a deleniti atque quod, totam eaque illo error voluptas pariatur nam. Non quia sed exercitationem sunt numquam pariatur.
      Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aspernatur quas officiis totam provident similique iure excepturi. Autem ducimus deleniti dolore iure unde cumque ex! Ab molestiae a qui repellat sed fugit mollitia corporis corrupti, quam repellendus sunt fuga, illum nemo, obcaecati rerum quibusdam. Veritatis esse, quos dolorem, possimus qui hic cum consectetur ducimus exercitationem dolor soluta laboriosam vero et? Voluptatem laudantium iure temporibus dolore ex quidem ad reprehenderit magnam aspernatur aliquam. Recusandae quis perspiciatis cupiditate, repellat quaerat iusto quibusdam reiciendis sunt, beatae minus veniam excepturi facilis? Voluptates similique pariatur rem dolore officiis nam itaque culpa vel eum hic eos aut quia consectetur voluptatum ab earum, placeat aspernatur debitis. Deserunt, minima sed. Deserunt quia quasi eum, sequi vel architecto eaque blanditiis nesciunt quis non dolor praesentium atque deleniti modi voluptates dolorem, cum optio temporibus? Odio fugit rem accusantium optio dolores veniam earum, dicta minima maxime iure consequatur esse ipsam natus voluptatibus ipsum labore illo in nobis quod iste. Amet, recusandae voluptates inventore consequuntur sed molestiae at temporibus doloremque consectetur qui aperiam perspiciatis, ad debitis. Sint quis velit fuga architecto dolore tempora incidunt nisi quasi quia! Beatae incidunt numquam, quia voluptas, quasi iusto eum unde optio at tenetur, excepturi animi quas?
    </div>
    </>
  )
}

export default App
